apiVersion: v1
kind: Service
metadata:
  name: chat-app-service
spec:
  type: NodePort
  selector:
    app: chat-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 32311  # Or let Kubernetes auto-assign (remove this line)
